name: YourWorldYourHome
favicon: null
layout_spectrum: 0.38311429019086063
typography_spectrum: 0.5916890003718436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7805289980024099
  lightness: 0.5626771266106516
  saturation: 0.8471960828173906
  rhythmicContrast: 0.7359942067414522
purpose: []
